export const ALL_COMPANIES = [
  { name: 'Four Sigma', hostname: '4sigma', stockSymbol: 'FSIG' },
  { name: 'AeroCorp', hostname: 'aerocorp', stockSymbol: 'AERO' },
  { name: 'Aevum Police Headquarters', hostname: 'aevum-police', stockSymbol: '' },
  { name: 'Alpha Enterprises', hostname: 'alpha-ent', stockSymbol: 'APHE' },
  { name: 'Applied Energetics', hostname: 'applied-energetics', stockSymbol: '' },
  { name: 'NiteSec', hostname: 'avmnite-02h', stockSymbol: '' },
  { name: 'Bachman & Associates', hostname: 'b-and-a', stockSymbol: '' },
  { name: 'Blade Industries', hostname: 'blade', stockSymbol: 'BLD' },
  { name: 'Catalyst Ventures', hostname: 'catalyst', stockSymbol: 'CTYS' },
  { name: 'Clarke Incorporated', hostname: 'clarkinc', stockSymbol: 'CLRK' },
  { name: 'CompuTek', hostname: 'computek', stockSymbol: 'CTK' },
  { name: 'Crush Fitness', hostname: 'crush-fitness', stockSymbol: '' },
  { name: 'CyberSec', hostname: 'CSEC', stockSymbol: '' },
  { name: 'darkweb', hostname: 'darkweb', stockSymbol: '' },
  { name: 'DefComm', hostname: 'defcomm', stockSymbol: 'DCOMM' },
  { name: 'DeltaOne', hostname: 'deltaone', stockSymbol: '' },
  { name: 'ECorp', hostname: 'ecorp', stockSymbol: 'ECP' },
  { name: 'FoodNStuff', hostname: 'foodnstuff', stockSymbol: 'FNS' },
  { name: 'Fulcrum Technologies', hostname: 'fulcrumassets', stockSymbol: '' },
  { name: 'Fulcrum Technologies', hostname: 'fulcrumtech', stockSymbol: 'FLCM' },
  { name: 'Galactic Cybersystems', hostname: 'galactic-cyber', stockSymbol: '' },
  { name: 'Global Pharmaceuticals', hostname: 'global-pharm', stockSymbol: 'GPH' },
  { name: 'HaraKiri Sushi Bar Network', hostname: 'harakiri-sushi', stockSymbol: '' },
  { name: 'Helios Labs', hostname: 'helios', stockSymbol: 'HLS' },
  { name: 'HongFang Teahouse', hostname: 'hong-fang-tea', stockSymbol: '' },
  { name: "Joe's Guns", hostname: 'joesguns', stockSymbol: 'JGN' },
  { name: 'I.I.I.I', hostname: 'I.I.I.I', stockSymbol: '' },
  { name: 'Icarus Microsystems', hostname: 'icarus', stockSymbol: 'ICRS' },
  { name: 'InfoComm', hostname: 'infocomm', stockSymbol: '' },
  { name: 'Iron Gym Network', hostname: 'iron-gym', stockSymbol: '' },
  { name: 'LexoCorp', hostname: 'lexo-corp', stockSymbol: 'LXO' },
  { name: 'Johnson Orthopedics', hostname: 'johnson-ortho', stockSymbol: '' },
  { name: 'KuaiGong International', hostname: 'kuai-gong', stockSymbol: 'KGI' },
  { name: 'Max Hardware Store', hostname: 'max-hardware', stockSymbol: '' },
  { name: 'MegaCorp', hostname: 'megacorp', stockSymbol: 'MGCP' },
  { name: 'Microdyne Technologies', hostname: 'microdyne', stockSymbol: 'MDYN' },
  { name: 'Millenium Fitness Network', hostname: 'millenium-fitness', stockSymbol: '' },
  { name: 'Noodle Bar', hostname: 'n00dles', stockSymbol: '' },
  { name: 'Nectar Nightclub Network', hostname: 'nectar-net', stockSymbol: '' },
  { name: 'Neo Nightclub Network', hostname: 'neo-net', stockSymbol: '' },
  { name: 'NetLink Technologies', hostname: 'netlink', stockSymbol: 'NTLK' },
  { name: 'Nova Medical', hostname: 'nova-med', stockSymbol: 'NVMD' },
  { name: 'NWO', hostname: 'nwo', stockSymbol: '' },
  { name: 'Omega Software', hostname: 'omega-net', stockSymbol: 'OMGA' },
  { name: 'Omnia Cybersystems', hostname: 'omnia', stockSymbol: 'OMN' },
  { name: 'OmniTek Incorporated', hostname: 'omnitek', stockSymbol: 'OMTK' },
  { name: 'Phantasy Club', hostname: 'phantasy', stockSymbol: '' },
  { name: 'Powerhouse Fitness', hostname: 'powerhouse-fitness', stockSymbol: '' },
  { name: 'Rho Construction', hostname: 'rho-construction', stockSymbol: 'RHOC' },
  { name: 'Rothman University', hostname: 'rothman-uni', stockSymbol: '' },
  { name: 'The Runners', hostname: 'run4theh111z', stockSymbol: '' },
  { name: 'Sigma Cosmetics', hostname: 'sigma-cosmetics', stockSymbol: 'SGC' },
  { name: 'Silver Helix', hostname: 'silver-helix', stockSymbol: '' },
  { name: 'Snap Fitness', hostname: 'snap-fitness', stockSymbol: '' },
  { name: 'Solaris Space Systems', hostname: 'solaris', stockSymbol: 'SLRS' },
  { name: 'Storm Technologies', hostname: 'stormtech', stockSymbol: 'STM' },
  { name: 'Summit University', hostname: 'summit-uni', stockSymbol: '' },
  { name: 'SysCore Securities', hostname: 'syscore', stockSymbol: 'SYSC' },
  { name: 'Taiyang Digital', hostname: 'taiyang-digital', stockSymbol: '' },
  { name: 'Helios', hostname: 'The-Cave', stockSymbol: '' },
  { name: 'The Hub', hostname: 'the-hub', stockSymbol: '' },
  { name: 'Titan Labratories', hostname: 'titan-labs', stockSymbol: 'TITN' },
  { name: 'UnitaLife Group', hostname: 'unitalife', stockSymbol: '' },
  { name: 'Universal Energy', hostname: 'univ-energy', stockSymbol: 'UNV' },
  { name: 'VitaLife', hostname: 'vitalife', stockSymbol: 'VITA' },
  { name: 'ZB Defense Industries', hostname: 'zb-def', stockSymbol: '' },
  { name: 'ZB Institute of Technology', hostname: 'zb-institute', stockSymbol: '' },
  { name: 'ZER0 Nightclub', hostname: 'zer0', stockSymbol: '' },
  { name: 'Zeus Medical', hostname: 'zeus-med', stockSymbol: '' },
  { name: 'Central Intelligence Agency', hostname: 'cia', stockSymbol: 'CIA' },
  { name: 'National Security Agency', hostname: 'nsa', stockSymbol: 'NSA' },
  { name: 'Watchdog Security', hostname: '', stockSymbol: 'WDS' },
  { name: 'Carmichael Security', hostname: '', stockSymbol: '' },
];

export const ALL_CORPORATIONS = [
  { name: 'Bachman & Associates', hostname: '', stockSymbol: '' },
  { name: 'ECorp', hostname: '', stockSymbol: '' },
  { name: 'MegaCorp', hostname: '', stockSymbol: '' },
  { name: 'KuaiGong International', hostname: '', stockSymbol: '' },
  { name: 'Four Sigma', hostname: '', stockSymbol: '' },
  { name: 'NWO', hostname: '', stockSymbol: '' },
  { name: 'Blade Industries', hostname: '', stockSymbol: '' },
  { name: 'OmniTek Incorporated', hostname: '', stockSymbol: '' },
  { name: 'Clarke Incorporated', hostname: '', stockSymbol: '' },
  { name: 'Fulcrum Technologies', hostname: '', stockSymbol: '' },
];
