export const ALL_FACTIONS = [
  'CyberSec',
  'Tian Di Hui',
  'Netburners',
  'Sector-12',
  'Chongqing',
  'New Tokyo',
  'Ishima',
  'Aevum',
  'Volhaven',
  'NiteSec',
  'The Black Hand',
  'BitRunners',
  'Bladeburners',
  'Slum Snakes',
  'Tetrads',
  'Speakers for the Dead',
  'The Dark Army',
  'The Syndicate',
  'The Covenant',
  'Daedalus',
  'Illuminati',
  'Bachman & Associates',
  'ECorp',
  'MegaCorp',
  'Blade Industries',
  'NWO',
  'Clarke Incorporated',
  'OmniTek Incorporated',
  'Four Sigma',
  'KuaiGong International',
  'Fulcrum Secret Technologies',
  'Silhouette',
  'Church of the Machine God',
];

export const LOCATION_FACTION_GROUPS = [['Sector-12', 'Aevum'], ['Chongqing', 'Ishima', 'New Tokyo'], ['Volhaven']];

export const ALL_LOCATION_FACTIONS = ['Sector-12', 'Aevum', 'Chongqing', 'Ishima', 'New Tokyo', 'Volhaven'];
